import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import StandardLayout from "../Components/layouts/standard-layout";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light" style={{ colorScheme: "light" }}>
      <body className={poppins.className}>
        
        <StandardLayout>{children}</StandardLayout>
      </body>
    </html>
  );
}
