import type { Metadata } from 'next'
import './globals.css'
import Providers from '../Components/providers'
import Footer from '../Components/footer'
import Header from '../Components/navbar'

import { Poppins } from 'next/font/google'
import CustomCursor from '../utils/use-mouse-position'

const poppins = Poppins({
	weight: '400',
	subsets: ['latin'],
	display: 'swap'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className="light" style={{ colorScheme: 'light' }}>
			<body className={poppins.className}>
				<Providers>
					{/* <CustomCursor /> */}
					<Header />
					{children}
				</Providers>
			</body>
		</html>
	)
}
