name: Deploy

on:
    push:
        branches:
            - 'master'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: User Node.js LTS
              uses: actions/setup-node@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm run lint

            - name: Linter Failure Alert
              if: ${{ failure() }}
              uses: tsickert/discord-webhook@v5.3.0
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  embed-title: '🚨🚨🚨 [NANDANIPALIWAL.CO] MASTER BRANCH LINTER FAILED 🚨🚨🚨'
                  embed-description: ' .<@517983211708612609> production linter failed, check [HERE](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'

    deploy:
        environment: Production
        timeout-minutes: 15
        runs-on: ubuntu-latest
        needs: [lint]
        env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: User Node.js LTS
              uses: actions/setup-node@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4

            - name: Install Vercel CLI
              run: pnpm -g add vercel@canary

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Trigger Production Deployment
              run: vercel deploy -y --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

            - name: Deployment Failure Alert
              if: ${{ failure() }}
              uses: tsickert/discord-webhook@v5.3.0
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  embed-title: '🚨🚨🚨 [NANDANIPALIWAL.CO] MASTER BRANCH DEPLOYMENT FAILED 🚨🚨🚨'
                  embed-description: ' .<@517983211708612609> production deployment failed, check [HERE](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
